server:
  port: 8124

spring:
  application:
    name: ai-translate
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  config:
    import: "optional:nacos:ai-prompts2.yaml"
  cloud:
    nacos:
      config:
        server-addr: 120.53.234.133:8848
        config:
          namespace: public
          file-extension: yaml
          group: DEFAULT_GROUP
          refresh: true
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ai_translate}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:your-api-key-here}
      chat:
        options:
          model: ${DASHSCOPE_MODEL:model}

mai-memo:
  api:
    base-url: https://open.maimemo.com/open/api/v1

minio:
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: 12345678
  bucket-name: translate-ai
