server:
  port: 8124

spring:
  application:
    name: ai-translate
  datasource:
    url: jdbc:mysql://localhost:3306/novel_translate
    username: root
    password: Momo123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    dashscope:
      api-key: sk-28653b7663bb407d874494b043b06b3b
      chat:
        options:
          model: deepseek-v4-flash-0731

redisson:
  singleServerConfig:
    address: "redis://localhost:6379"
    password: "123456"
    database: 0
    connectionPoolSize: 8
    connectionMinimumIdleSize: 2

mai-memo:
  api:
    base-url: https://open.maimemo.com/open/api/v1

minio:
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: 12345678
  bucket-name: translate-ai